services:
  Helmd:
    build: .
    container_name: Helmd
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - Helmd_data:/data
    environment:
      - HELMD_PORT=9117

volumes:
  Helmd_data:
